### ISSUE TITLE
Discord link expired or invalid

### ISSUE THREAD

**Issue by cristianchelu** [Jezza34000/homeassistant_petkit#13]
### Checklist

- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This request is not a duplicate feature request of [previous feature requests](https://github.com/Jezza34000/homeassistant_petkit/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

https://discord.gg/bYQWBc9d

> This invite may be expired, or you might not have permission to join.

### Describe the solution you'd like

New link? :)

**Comment by Jezza34000** [comment]
This should be better... I didn't know there was an expiration setting on Discord links
