### ISSUE TITLE
Does not recognize the feeder

### ISSUE THREAD

**Issue by joasara** [Jezza34000/homeassistant_petkit#6]
## System Information

version | core-2024.12.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.13.0
os_name | Linux
os_version | 6.6.66-haos
arch | x86_64
timezone | Europe/Madrid
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.1
Stage | running
Available Repositories | 1498
Downloaded Repositories | 50

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 14.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.12.0
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 146.9 GB
disk_used | 41.5 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | kvm
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.8.0), Advanced SSH & Web Terminal (19.0.0), Mosquitto broker (6.4.1), Samba share (12.3.2), Node-RED (18.1.1), Home Assistant Google Drive Backup (0.112.1), MariaDB (2.7.1), Zigbee2MQTT (1.42.0-2), ESPHome Device Builder (2024.12.2), Studio Code Server (5.17.3), Network UPS Tools (0.14.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 28
views | 31
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 11 de diciembre de 2024, 20:39
-- | --
current_recorder_run | 22 de diciembre de 2024, 09:26
estimated_db_size | 4674.14 MiB
database_engine | mysql
database_version | 10.11.6

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/Jezaa34000/homeassistant_petkit/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

The previous integration worked with the "Fresh Element Infinity" feeder but is now not recognized in Homeassistant. It is not listed on the devices. It is the same account that I used previously and in the mobile APP, with another account with which I have shared the devices, if it works correctly.

### Reproduction steps

1 - Just configure the account.

### Debug logs

```text
There is no error from this integration.
```

**Comment by Jezza34000** [comment]
Hello,
Which feeder model is it ?

**Comment by joasara** [comment]
Fresh Element Infinity--> https://www.amazon.es/PETKIT-Fresh-Element-Infinity-Dispensador/dp/B09R4LPBCD

**Comment by Jezza34000** [comment]
OK can you send me a message on Discord channel ?

**Comment by joasara** [comment]
what is the channel?

**Comment by Jezza34000** [comment]
https://discord.com/invite/bYQWBc9d

**Comment by Jezza34000** [comment]
Fixed with last release : https://github.com/Jezza34000/homeassistant_petkit/releases/tag/1.3.4
